version: '3.7'

services:
  api:
    container_name: nest_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /dist
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    command: npm run start:docker
    env_file:
      - .env
    networks:
      - desafio-gestao-produtos-network
    depends_on:
      - postgres

  db:
    container_name: nest_db
    image: postgres:16.0-alpine3.17
    networks:
      - desafio-gestao-produtos-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - api_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "teste"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - desafio-gestao-produtos-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin


networks:
  desafio-gestao-produtos-network:
volumes:
  api_db_data:
  pgadmin-data:
